### PR TITLE
Image support

### PR DESCRIPTION
**Pull request by ihabunek**
Rebased and squashed #319 since its history was getting very messy.

### CODE REVIEW

**Comment by ihabunek** [comment]
I'll periodically rebase this on master to avoid getting conflicted again.

**Comment by ihabunek** [comment]
@danschwarz Doing some work on this branch so I'll need to rebase again. Just FYI. Sorry if i break your stuff.

I'm trying to make it so that image support is optional so TUI works without term_image installed.

**Comment by danschwarz** [comment]
Ok, I'm fine with anything that gets image support into the master branch- I'll check for any breakage.

**Comment by danschwarz** [comment]
See #389

**Comment by ihabunek** [comment]
Merged manually, thanks for this. Sorry for dragging my feet on this one.

**Pull request closed without merging**
