### PR TITLE
Add installation instructions for FreeBSD

### PR DESCRIPTION
**Pull request by 0mp**

### CODE REVIEW

**Comment by 0mp** [comment]
https://www.freshports.org/net-im/toot/

**Comment by ihabunek** [comment]
Thanks! Much appreciated.

**Comment by ihabunek** [comment]
Would you like me to add a note that you maintain the freebsd port?

**Comment by 0mp** [comment]
@ihabunek Certainly! Thank you! It's either 0mp@FreeBSD.org or mpts on mastodon.social. Your call :)

BTW, toot is pretty cool!

**Pull request merged**
