### PR TITLE
Fix left column padding in timeline with wide characters

### LINKED ISSUE #45: Wide characters break layout
e.g. chinese and japanese script, some emojis, etc.

Check out:
https://github.com/jquast/wcwidth

### PR DESCRIPTION
**Pull request by dlax**
Fixes #45.

### CODE REVIEW

**Comment by ihabunek** [comment]
@dlax I like this PR, but i wanted to test some edge cases and haven't gotten around to it yet. Thanks for the patience.

**Comment by dlax** [comment]
@ihabunek, no problem. Take your time :)

**Comment by ihabunek** [comment]
FYI, I took your patches, and made some improvement and cleanup in #92. Did not merge yet, because the next problem with having wide chars is wrapping text, since the standard wrapper does not respect wide chars.

**Comment by ihabunek** [comment]
Merged manually with minor tweaks. Thanks for the work again :)

**Pull request closed without merging**
