### PR TITLE
Improve handling of reblogs in TUI 

### PR DESCRIPTION
**Pull request by dlax**
A couple of changes to improve handling of reblogs in the urwid TUI, mostly to retrieve data from the original status (the one that's reblogged) instead of from the reblog.

### CODE REVIEW

**Comment by ihabunek** [comment]
Thanks, I'll have a look at both PRs soon. It's been a busy time for me lately.

**Comment by dlax** [comment]
No problem, take your time!

**Comment by ihabunek** [comment]
@dlax This seems add more and more code to handle the same problem for various fields. What do you think about this approach?
https://github.com/ihabunek/toot/pull/130

**Comment by dlax** [comment]
> What do you think about this approach? https://github.com/ihabunek/toot/pull/130

That's indeed cleaner and more explicit as it does not shadow
information of the reblogging status.

**Comment by ihabunek** [comment]
OK. Going forward with that version. Thanks for this though.

**Pull request closed without merging**
