### PR TITLE
install CHANGELOG.md and LICENSE (fixes #149)

### LINKED ISSUE #149: data files get added to wrong directory
when installing using 
`python setup.py install --root="somedir/" --optimize=1 --skip-build`

the following files are in somedir, that should not belong there:

somedir/usr/CHANGELOG.md
somedir/usr/LICENSE

The license should be at /usr/share/licenses.

### PR DESCRIPTION
**Pull request by bill-auger**
fixes #149

### CODE REVIEW

**Comment by ihabunek** [comment]
Thanks. I need to read up on this before deciding whether to merge.

**Comment by dlax** [comment]
Installing the LICENSE this way seems wrong (never seen this in a python project). Also, the file is already present in `.dist-info` directory (e.g. `$VIRTUAL_ENV/lib/python3.7/site-packages/toot-0.25.2.dist-info/LICENSE`).

The changelog file could be moved in docs/ directory maybe?

**Comment by ihabunek** [comment]
> The changelog file could be moved in docs/ directory maybe?

Hm, I could do that. That would also make the changelog accessible on [readthedocs](https://toot.readthedocs.io/en/latest/).

**Comment by ihabunek** [comment]
Thanks for the work, but I'll pass on these changes for now.

**Pull request closed without merging**
