### PR TITLE
React properly to 422: Validation Failed. Status has already been tak…

### PR DESCRIPTION
**Pull request by danschwarz**
This addresses issue https://github.com/ihabunek/toot/issues/256

### CODE REVIEW

**Comment by danschwarz** [comment]
Updated to ignore more kinds of 422 validation failed errors and to merge cleanly into latest master.

**Comment by ihabunek** [comment]
I had to revert this :/ It broke the --json option which expects a response to be returned.

**Comment by danschwarz** [comment]
That's unfortunate. If I recall correctly, this PR was a bit of a kludge due to the way the API works. I'll have to see if there's a better way to implement that is more compatible.

**Comment by danschwarz** [comment]
Thinking about getting rid of ApiError and NotFoundError exception throwing, as these are the root cause of the incompatibility with --json. 

What do you think?

**Pull request merged**
